name: Daily Update

on:
  schedule:
    - cron: "0 12 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      LOGS_DIR: /tmp/android_prebuilts_prebuiltapks/logs
      LOGS_FILE: /tmp/android_prebuilts_prebuiltapks/logs/build-perf.log
    steps:
      - uses: actions/checkout@master
      - name: Setup NodeJS 14
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: List main variables
        run: |
          echo "SHA:     : ${GITHUB_SHA}"
          echo "Reference: ${GITHUB_REF}"
          echo "Event    : ${GITHUB_EVENT_NAME}"

      - name: Set git user information
        run: |
          git config --global user.name SuperITMan
          git config --global user.email admin@superitman.com

      - name: Run script update-packages
        run: bash ./.scripts/update-packages.sh

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}